language: cpp

compiler:
  - gcc
  addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        - llvm-toolchain-trusty-6.0
        packages: 
          - libstdc++-7-dev

before_script:
  - mkdir build
  - cd build
  - cmake ..

script: make

